### ISSUE TITLE
TypeError: (0 , _relaxFramework.mergeFragments) is not a function

### ISSUE THREAD

**Issue by starzou** [relax/relax#116]
```bash
➜  relax git:(redux) ✗ npm run dev

> relax@1.0.0 dev /Users/foo/relax
> grunt dev

Running "less:development" (less) task
File public/css/main.css created

Running "browserify:common" (browserify) task
>> Bundle public/js/common.js created.

Running "browserify:development" (browserify) task
>> Bundle public/js/public.js created.
>> Bundle public/js/auth.js created.
>> Bundle public/js/admin.js created.

Running "copy:main" (copy) task
Created 3 directories, copied 8 files

Running "concurrent:dev" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    Running "watch" task
    Waiting...
    [nodemon] v1.3.8
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `node index.js dev`
    /Users/foo/relax/lib/components/admin/panels/media/list.jsx:134
        value: (0, _relaxFramework.mergeFragments)(_mediaItem2['default'].fragments),
                                                  ^
    
    TypeError: (0 , _relaxFramework.mergeFragments) is not a function
        at /Users/foo/relax/lib/components/admin/panels/media/list.jsx:8:22
        at Object.<anonymous> (/Users/foo/relax/lib/components/admin/panels/media/list.jsx:7:31)
        at Module._compile (module.js:435:26)
        at normalLoader (/Users/foo/relax/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
        at Object.require.extensions.(anonymous function) [as .jsx] (/Users/foo/relax/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/foo/relax/lib/components/admin/panels/media/index.jsx:8:41)
        at Module._compile (module.js:435:26)
        at normalLoader (/Users/foo/relax/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
        at Object.require.extensions.(anonymous function) [as .jsx] (/Users/foo/relax/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/foo/relax/lib/containers/admin/media-manager.jsx:8:54)
        at Module._compile (module.js:435:26)
        at normalLoader (/Users/foo/relax/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
        at Object.require.extensions.(anonymous function) [as .jsx] (/Users/foo/relax/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
        at Module.load (module.js:356:32)
    [nodemon] app crashed - waiting for file changes before starting...
```

node version is v4.2.1

**Comment by bruno12mota** [comment]
Are you installing the redux refactor branch?

**Comment by starzou** [comment]
Yes.  I run successfully in master branch.
But start,run too slow.
@bruno12mota thx.

**Comment by bruno12mota** [comment]
Redux branch is yet undergoing, we'll merge it in master when it is done. You can see what's missing for it on the Refactor milestone

**Comment by magalhas** [comment]
@starzou to go over that problem you should cp `relax-framework` redux branch inside `relax` node_modules directory. It's tricky because of peerDependencies. `npm link` won't work :(

**Comment by magalhas** [comment]
As soon as we update to node4 and npm3 this complication will be gone.

**Comment by bruno12mota** [comment]
Closing this one, redux branch will be merged on master in about one week
