### ISSUE TITLE
Error: Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by sgr0691** [relax/relax#233]
I'm having issues fulling install Relax and now I have this error message but I'm not sure how to fix it. Can someone please help me?

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by bruno12mota** [comment]
That seems to be a dependency from the relax's rimraf dependency. Which version of node/npm are you using?

**Comment by sgr0691** [comment]
Hi Bruno Im currently using node v6

**Comment by jonjaques** [comment]
Ever since `npm@3` I've noticed weird instances of it not doing complete installs, especially if it gets tripped up on something the first time or you're using any `npm link`s. Just spitballing here, but try `rm -rf node_modules && npm install`. Obviously pull first :)

**Comment by sgr0691** [comment]
Hi Jon,

Thanks so much for your help but its still giving me an error. 

error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Sergios-MBP:~ SergioR$ rm -rf node_modules && npm install
module.js:440
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by sgr0691** [comment]
THanks Jon but its still giving me the same error message. 

Sergios-MBP:Relax SergioR$ rm -rf node_modules && npm install
module.js:440
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by bruno12mota** [comment]
Hey! Don't think that's a problem with Relax. Try running the following after pulling master again:

```bash
rm -rf node_modules && npm cache clear && npm install
```

If this doesn't do the job really no clue what might be the issue.

**Comment by bruno12mota** [comment]
node v6 installation issue should be resolved now
