### ISSUE TITLE
error on launch

### ISSUE THREAD

**Issue by rdewolff** [relax/relax#242]
Hi

Trying to check your very nice project. After cloning the repo, installing the required lib via `brew`, added the `.relaxrc` file, I try to start the project but it fails with the following error. I have even deleted the whole `node_modules` folder and reinstalled but without success.

```
npm start

> relax@0.0.0 start /Users/rdewolff/Projects/relax
> cross-env NODE_ENV=production node build/app

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/rdewolff/Projects/relax/build/app'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! relax@0.0.0 start: `cross-env NODE_ENV=production node build/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the relax@0.0.0 start script 'cross-env NODE_ENV=production node build/app'.
npm ERR! This is most likely a problem with the relax package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node build/app
npm ERR! You can get their info via:
```

.relaxrc file :
```
{
  "port": 8080,
  "devPort": 8181,
  "db": {
    "uri": "mongodb://localhost/relax"
  }
}
```

Any idea what's the problem?

**Comment by bruno12mota** [comment]
Hey! Try running `npm run dev` instead. Production build is still not configured.

**Comment by rdewolff** [comment]
Works!
