### ISSUE TITLE
Error: Cannot find module "lodash.isarray"

### ISSUE THREAD

**Issue by ruiabrantes** [relax/relax#249]
I have this error message when I try to install a full version of Relax:

```../lib/index.js:159
export function buildQueryAndVariables (fragments, inputVariables = {}, type = 'query') {
       ^
Error: Cannot find module "lodash.isarray"
    at webpackMissingModule (../lib/index.js:159:8)
    at Object.<anonymous> (../lib/index.js:159:8)
    at __webpack_require__ (../lib/index.js:159:17)
    at Object.<anonymous> (../lib/index.js:159:8)
    at __webpack_require__ (../lib/index.js:159:17)
    at Object.defineProperty.value (../lib/index.js:159:8)
    at __webpack_require__ (../lib/index.js:159:17)
    at Object.defineProperty.value (../lib/index.js:45:8)
    at __webpack_require__ (../lib/index.js:159:17)
    at Object.defineProperty.value (../lib/index.js:27:8)
    at ../lib/index.js:27:8
    at webpackUniversalModuleDefinition (/Users/ruiabrantes/Documents/_DEVELOPER/Relax/node_modules/relate-js/dist/index.js:3:20)
    at Object.<anonymous> (../lib/index.js:27:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```
version of node: `4.4.5`

I already tried `rm -rf node_modules && npm cache clear && npm install` but nothing seems to work.

Any ideas?

Thanks

**Comment by bruno12mota** [comment]
Hi @ruiabrantes, happened to me with another project as well yesterday, I presume it's a dependency version that is bugged out. In the other project I ended up locking all dependencies to the version I had in the package.json. Will try to check which on is and fix it ;)

**Comment by ruiabrantes** [comment]
ok, cool.

Thanks.

**Comment by ruiabrantes** [comment]
@bruno12mota I saw you locked down all dependencies but if you roll back `relate-js` to `0.5.0` release apparently it works... but I didn't make any huge tests.

**Comment by bruno12mota** [comment]
Will test it out. Since I couldn't locate the error I locked down the dependencies, gonna check if it's something with Relate, thanks!

**Comment by bruno12mota** [comment]
You were right 😃  it was indeed a bugged build of Relate. I bumped the version and re published and it's working. Thanks!

**Comment by ruiabrantes** [comment]
@bruno12mota no worries..
