### ISSUE TITLE
Error when start Relax.

### ISSUE THREAD

**Issue by vanloc0301** [relax/relax#257]
I have error like this when run command: `npm install` => `npm run dev`:

I was installed MongoDB and platform is Windows.

Thank you very much.

```
(> relax@0.0.0 startDev D:\relax
> cross-env NODE_ENV=development node build/app

(node:182360) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, 
plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
debug: Listening at port 8080
error: uncaughtException: connect ECONNREFUSED 127.0.0.1:27017 date=Tue Jul 05 2016 01:48:10 GMT+0700 (SE Asia Standard Time), 
pid=182360, uid=null, gid=null, cwd=D:\relax, execPath=C:\Program Files\nodejs\node.exe, version=v6.2.2, argv=[C:\Program Files\nodejs\node.exe, D:\relax\build\app], 
rss=170266624, heapTotal=147234816, heapUsed=122231608, loadavg=[0, 0, 0], uptime=35174.5791726, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=1007, method=exports._errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=1030, method=_exceptionWithHostPort, native=false, column=14, file=net.js, function=TCPConnectWrap.afterConnect [as oncomplete], line=1080, method=afterConnect [as oncomplete], native=false], stack=[Error: connect ECONNREFUSED 127.0.0.1:27017,     at Object.exports._errnoException (util.js:1007:11),     at exports._exceptionWithHostPort (util.js:1030:20),    
 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)]
::ffff:127.0.0.1 - GET / HTTP/1.1 - - - - ms
)
```

**Comment by vanloc0301** [comment]
This problem because I'm not setting MongoDB.

In linux, start it in terminal with: `mongod`. And run `npm run dev`.
