### ISSUE TITLE
"TypeError: Cannot read property 'toUpperCase' of undefined" at demo

### ISSUE THREAD

**Issue by bebraw** [relax/relax#37]
I tried viewing a page known as "jjjj" through http://demo.getrelax.io/admin/pages . That opened http://demo.getrelax.io/jjjj in a new tab showing the following error:

```
TypeError: Cannot read property 'toUpperCase' of undefined
   at autoGenerateWrapperClass (/home/node/apps/relax/source/node_modules/react/lib/ReactDefaultInjection.js:53:18)
   at Object.getComponentClassForElement (/home/node/apps/relax/source/node_modules/react/lib/ReactNativeComponent.js:59:49)
   at [object Object].ReactCompositeComponentMixin._processProps (/home/node/apps/relax/source/node_modules/react/lib/ReactCompositeComponent.js:429:44)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactCompositeComponent.js:127:28)
   at [object Object].wrapper [as mountComponent] (/home/node/apps/relax/source/node_modules/react/lib/ReactPerf.js:70:21)
   at Object.ReactReconciler.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactReconciler.js:38:35)
   at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/node/apps/relax/source/node_modules/react/lib/ReactMultiChild.js:192:44)
   at ReactDOMComponent.Mixin._createContentMarkup (/home/node/apps/relax/source/node_modules/react/lib/ReactDOMComponent.js:289:32)
   at ReactDOMComponent.Mixin.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactDOMComponent.js:199:12)
   at Object.ReactReconciler.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactReconciler.js:38:35)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactCompositeComponent.js:247:34)
   at [object Object].wrapper [as mountComponent] (/home/node/apps/relax/source/node_modules/react/lib/ReactPerf.js:70:21)
   at Object.ReactReconciler.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactReconciler.js:38:35)
   at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/node/apps/relax/source/node_modules/react/lib/ReactMultiChild.js:192:44)
   at ReactDOMComponent.Mixin._createContentMarkup (/home/node/apps/relax/source/node_modules/react/lib/ReactDOMComponent.js:289:32)
   at ReactDOMComponent.Mixin.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactDOMComponent.js:199:12)
   at Object.ReactReconciler.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactReconciler.js:38:35)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactCompositeComponent.js:247:34)
   at [object Object].wrapper [as mountComponent] (/home/node/apps/relax/source/node_modules/react/lib/ReactPerf.js:70:21)
   at Object.ReactReconciler.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactReconciler.js:38:35)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactCompositeComponent.js:247:34)
   at [object Object].wrapper [as mountComponent] (/home/node/apps/relax/source/node_modules/react/lib/ReactPerf.js:70:21)
   at Object.ReactReconciler.mountComponent (/home/node/apps/relax/source/node_modules/react/lib/ReactReconciler.js:38:35)
```

I recall this error might have something to do with React component definitions (passing an object instead of a React element).

**Comment by bruno12mota** [comment]
Thanks for noticing, it was from the menu element, which wasn't rendering anything since no menu was selected (react errors out of course on this situation), will fix it

**Comment by bruno12mota** [comment]
Fixed, was a problem on the deploy
