### ISSUE TITLE
Module.JS error

### ISSUE THREAD

**Issue by aj-jhaveri** [relax/relax#426]
Hi, i followed the instructions and when I execute the following command yarn start, I get the following error:

$ cross-env NODE_ENV=production node build/app 
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/aj/relax/build/app'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 1.

Any idea how I can fix this?

**Comment by 4levels** [comment]
Hi,

Can you elaborate on this?
To me this seems yarn related as the cross-env call looks very standard and states that it can't find something.

Did yarn build run correctly? What OS are you working with? Do you have other yarn projects working locally? Etc etc ;-)

If you find the solution, please leave a hint here as well

Thanks!

**Comment by aj-jhaveri** [comment]
I followed the installation guide here: https://yarnpkg.com/ and created a
.bash_profile file with the following: export PATH="$PATH:`yarn global bin`"

and installed MongoDB with brew according to (
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/), started
it, then executed:

yarn, yarn build, and yarn start

according to your doc. And then received that error. Was there something I
missed or did incorrectly?

Best Regards,

*Anish Jhaveri | slakedesign.com <http://slakedesign.com/> | Full Stack
Developer*

*817.371.0013* <8173710013> Mobile | 512.759.6309 <5127596309> Office

701 Brazos St | 16th Floor | Austin, TX 78701

*contact@slakedesign.com <contact@slakedesign.com>*


<http://www.linkedin.com/in/anishjhaveri360>

This e-mail and/or its attachment(s) contain confidential information, and
is intended only for the individual indicated. If you are not the intended
recipient, you are hereby notified that the disclosure, copying,
distribution or use of the contents of this transmission is strictly
prohibited, and no privilege or protection has been waived. If you have
received this communication in error, please notify the sender immediately
and then delete the message from your computer.

**Comment by aj-jhaveri** [comment]
And I am using MacOS Sierra, and do not have any other yarn projects. And
here was the output:

comp:relax aj$ yarn

*yarn install v0.19.1*

[1/4] 🔍  Resolving packages...

[2/4] 🚚  Fetching packages...

[3/4] 🔗  Linking dependencies...

warning "relate-js@0.7.6" has incorrect peer dependency "react-redux@
^4.0.0".

[4/4] 📃  Building fresh packages...

✨  Done in 90.86s.

comp:relax aj$ yarn start

*yarn start v0.19.1*

$ cross-env NODE_ENV=production node build/app

module.js:471

    throw err;

    ^


Error: Cannot find module '/Users/aj/relax/build/app'

    at Function.Module._resolveFilename (module.js:469:15)

    at Function.Module._load (module.js:417:25)

    at Module.runMain (module.js:604:10)

    at run (bootstrap_node.js:394:7)

    at startup (bootstrap_node.js:149:9)

    at bootstrap_node.js:509:3

error Command failed with exit code 1.

Best Regards,

*Anish Jhaveri | slakedesign.com <http://slakedesign.com/> | Full Stack
Developer*

*817.371.0013* <8173710013> Mobile | 512.759.6309 <5127596309> Office

701 Brazos St | 16th Floor | Austin, TX 78701

*contact@slakedesign.com <contact@slakedesign.com>*


<http://www.linkedin.com/in/anishjhaveri360>

This e-mail and/or its attachment(s) contain confidential information, and
is intended only for the individual indicated. If you are not the intended
recipient, you are hereby notified that the disclosure, copying,
distribution or use of the contents of this transmission is strictly
prohibited, and no privilege or protection has been waived. If you have
received this communication in error, please notify the sender immediately
and then delete the message from your computer.

**Comment by 4levels** [comment]
Hi, 

Did you run yarn build? Have you tried running yarn build again? I'm no expert whatsoever but it seems yarn build did not generate the missing file /Users/aj/relax/build/app

Can you verify if it exists and if the permissions allow reading it?

Kind regards,

Erik

**Comment by 4levels** [comment]
Have you tried Googling for "yarn start Error: Cannot find module build/app"?

**Comment by aj-jhaveri** [comment]
Ya, that was the first thing I did.

Best Regards,

*Anish Jhaveri | slakedesign.com <http://slakedesign.com/> | Full Stack
Developer*

*817.371.0013* <8173710013> Mobile | 512.759.6309 <5127596309> Office

701 Brazos St | 16th Floor | Austin, TX 78701

*contact@slakedesign.com <contact@slakedesign.com>*


<http://www.linkedin.com/in/anishjhaveri360>

This e-mail and/or its attachment(s) contain confidential information, and
is intended only for the individual indicated. If you are not the intended
recipient, you are hereby notified that the disclosure, copying,
distribution or use of the contents of this transmission is strictly
prohibited, and no privilege or protection has been waived. If you have
received this communication in error, please notify the sender immediately
and then delete the message from your computer.

**Comment by bruno12mota** [comment]
Hey @aj-jhaveri you need to run `yarn build` before running `yarn start` otherwise there won't be anything in the build folder.

**Comment by aj-jhaveri** [comment]
Ya, I ended up doing that but now I get a completely blank screen once
accessing the site.

Best Regards,

*Anish Jhaveri | slakedesign.com <http://slakedesign.com/> | Full Stack
Developer*

*817.371.0013* <8173710013> Mobile | 512.759.6309 <5127596309> Office

701 Brazos St | 16th Floor | Austin, TX 78701

*contact@slakedesign.com <contact@slakedesign.com>*


<http://www.linkedin.com/in/anishjhaveri360>

This e-mail and/or its attachment(s) contain confidential information, and
is intended only for the individual indicated. If you are not the intended
recipient, you are hereby notified that the disclosure, copying,
distribution or use of the contents of this transmission is strictly
prohibited, and no privilege or protection has been waived. If you have
received this communication in error, please notify the sender immediately
and then delete the message from your computer.

**Comment by 4levels** [comment]
Hi @aj-jhaveri,

can you access the admin by adding /admin after the url of your project?
It's normal that without content all you'll see is a white page..

Glad you're getting things working!
