### ISSUE TITLE
MongoError: Unknown modifier: $pushAll

### ISSUE THREAD

**Issue by MrPistoul** [relax/relax#445]
Hi guys i have this error with Mongodb 3.6 when i publish.
 ::1 - POST /graphql HTTP/1.1 200 339 - 7.603 ms
[1] MongoError: Unknown modifier: $pushAll
[1]     at Function.MongoError.create (****/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)

One idea ?

**Comment by magalhas** [comment]
That's due to MongoDB version. That operator was deprecated in the newer versions. Use a former one. I know that at least v3.2 supports `$pushAll`.

**Comment by diegofertr** [comment]
In this version of mongo, when creating the Schema you must bear in mind this:

`const eSchema = new mongoose.Schema ({
        model...
 }, {
      usePushEach: true
})`

**Comment by rivers-lis** [comment]
Всем привет, подскажите пожалуйста как исправить ошибку Unknown modifier: $pushAll

**Comment by rivers-lis** [comment]
Пробовал вот так не работает
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const UserSchema = new Schema({
    telegramId: {
        type: Number,
        required: true,
        usePushEach: true
    },

    films: {
        type: [String],
        default: []
    }
})

mongoose.model('users', UserSchema)

**Comment by DOSputin** [comment]
@rivers-lis 
попробуй это
try this:
`docker run -d --name mongo3.2 mongo:3.2`

**Comment by a7mdalqrny** [comment]
> Hi guys i have this error with Mongodb 3.6 when i publish. ::1 - POST /graphql HTTP/1.1 200 339 - 7.603 ms [1] MongoError: Unknown modifier: $pushAll [1] at Function.MongoError.create (****/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
> 
> One idea ?
